config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'films#index'

  get '/search', to: 'films#search', as: "search"
  get '/my_favs', to: 'films#fav_films', as: "my_favs"

  post '/:imdb/fav', to: "films#create_fav", as: "fav"
  post '/:imdb/unfav', to: "films#destroy_fav", as: "unfav"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fav.rb
class Fav < ApplicationRecord
  belongs_to :user, foreign_key: "user_id"
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :favs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :authenticate_user!, only: [:create_fav, :destroy_fav, :fav_films]
  before_action :find_fav, only: [:destroy_fav]

  def index
  end
  
  def search
    params[:page] = Integer(params[:page]) rescue 1
    films = search_film_by_title(params[:title], params[:page])
    @pages = (films["totalResults"].to_f / 10).ceil rescue 0
    
    if films.nil?
      redirect_to root_path
    end
  
    @film_list = films
  end

  def fav_films
    user_imdb_array = current_user.favs.pluck(:imdb_id)
    @fav_films = search_film_by_imdb(user_imdb_array)
  end

  def create_fav
    if already_fav?
      back_redirection
    else
      current_user.favs.create(user_id: current_user.id, imdb_id: params[:imdb])
    end

    back_redirection
  end

  def destroy_fav
    if not already_fav?
      back_redirection
    else
      @fav.destroy
    end

    back_redirection
  end
  
  
  private
    def request_api(url)
      response = Excon.get(url)
      parsed_response = JSON.parse(response.body)
      
      if parsed_response['Response'] != 'True'
        return nil
      else
        parsed_response
      end
      
    end
    
    def search_film_by_title(title, page = 1)
      request_api("http://www.omdbapi.com/?apikey=#{ENV["OMDB_API_KEY"]}&type=movie&s=#{URI.encode_www_form_component(title)}&page=#{page}")
    end

    def search_film_by_imdb(imdb)
      l = []
      if imdb.count > 0
        imdb.each do |f|
          l.append(request_api("http://www.omdbapi.com/?apikey=#{ENV["OMDB_API_KEY"]}&i=#{f}"))
        end

        return l
      end
    end

    def already_fav?
      Fav.where(user_id: current_user.id, imdb_id: params[:imdb]).exists?
    end

    def find_fav
      @fav = current_user.favs.find_by_imdb_id(params[:imdb])
    end

    def back_redirection
      redirect_back(fallback_location: root_path)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.where(favorite: true)
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.favorite
      @movie.update(favorite: false)
    else
      @movie.update(favorite: true)
    end
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if params[:query].present?
      @movies = Movie.where(favorite: false)
      @movies.destroy_all
      @data = JSON.parse(fetch_movies(params[:query]))
      if(@data["Response"] != "False")
        @data["Search"].each do |m|
        @movie = Movie.new(title: m["Title"], year: m["Year"], poster: m["Poster"], tipo: m["Type"])
        @movie.save
        end
      end
    end
    @movies = Movie.all.order(favorite: :desc)
  end

  def fetch_movies(title)
    RestClient.get "http://www.omdbapi.com/?s=#{title}&apikey=#{ENV["OMDB_APIKEY"]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_film_card.html.erb
<div class="flex flex-col my-5 rounded-md max-w-sm min-h-96 justify-between">
  <div>
    <div class="flex justify-center p-2 h-96">
      <% if film["Poster"] != "N/A" %>
        <%= image_tag(film["Poster"], class: "rounded-md shadow-lg border-2 border-gray-300") %>
      <% else %>
      <div class="flex justify-center items-center bg-gray-300 p-10 w-3/4 rounded-md select-none">
        <p class="text-gray-500 font-extralight text-2xl">No Image</p>
      </div>
      <% end %>
    </div>

    <div class="flex justify-center">
      <%= render "like_action", film: film %>
    </div>

    <div class="text-center px-5 pb-2">
      <span class="text-xl font-medium"><%= film["Title"] %></span>
      <span> - <%= film["Year"] %></span>
      <span>(<%= film["Type"] %>)</span>
    </div>
  </div>
</div>

app/views/films/_like_action.html.erb
<% if user_signed_in? %>
  <% if current_user.favs.find { | f | f.imdb_id == film["imdbID"]} %>
    <%= button_to unfav_path(film["imdbID"]), method: "POST" do %>
      <span class="text-red-600 shadow-lg">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd" />
        </svg>
      </span>
    <% end %>
  <% else %>
    <%= button_to fav_path(film["imdbID"]), method: "POST" do  %>
      <span class="text-gray-400 hover:text-red-600">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
        </svg>
      </span>
    <% end %>
  <% end%>
<% end %>

app/views/films/_navbar.html.erb
<header class="w-full flex bg-gradient-to-r from-purple-500 to-pink-500 opacity-95 shadow-md fixed top-0 h-10">
  <div class="w-full flex flex-row justify-between items-center container mx-auto">
    <% if user_signed_in? %>
      
      <div class="flex flex-row w-full justify-between px-5">
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "text-white font-medium" %>
        <div class="flex flex-row justify-end">
          <%= link_to "My Favs", my_favs_path, class: "px-5 rounded bg-purple-500 hover:bg-purple-700 text-white cursor-pointer mr-5" %>
          <%= link_to root_path do %>
            <div class="sm:hidden bg-white rounded-sm px-2">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </div>
          <% end %>
          <div class="hidden sm:block">
            <%= render "/films/search_form" %>
          </div>
        </div>
      </div>

    <% else %>
      <div class="flex flex-row w-full justify-between px-5">
        <%= button_to "Inicia Sesión", new_user_session_path, method: "GET", class: "px-2 rounded cursor-pointer transition easy-in-out bg-blue-300 hover:bg-red-300" %>
        <%= link_to "Search", root_path, class: "sm:hidden px-2 rounded cursor-pointer bg-white" %>
        <div class="hidden sm:block">
          <%= render "/films/search_form" %>
        </div>
      </div>
    <% end %>

  </div>
</header>

app/views/films/_pagination.html.erb
<div class="flex flex-row justify-center items-center gap-4">
  <% if params[:page].to_i > 1 %>
    <%= link_to controller: "films", action: "search", :page => params[:page].to_i - 1, :title => params[:title] do %>
      <button class="bg-black text-white p-2 px-5 rounded-md mx-5">back</button>
    <% end %>

    <%= link_to controller: "films", action: "search", :page => 1, :title => params[:title] do %>
      <p class="text-gray-400 hover:text-black">1</p>
    <% end %>
  <% end %>
  
  <%= params[:page] %>

  <% if params[:page].to_i < @pages %>
    <%= link_to controller: "films", action: "search", :page => @pages, :title => params[:title] do %>
      <p class="text-gray-400 hover:text-black"><%= @pages %></p>
    <% end %>

    <%= link_to controller: "films", action: "search", :page => params[:page].to_i + 1, :title => params[:title] do %>
      <button class="bg-black text-white p-2 px-5 rounded-md mx-5">next</button>
    <% end %>
  <% end %>
</div>

app/views/films/_search_form.html.erb
<div class="w-full">
  <%= form_tag(search_path, method: :get) do %>
    <%= text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Eg. Pulp Fiction", class: "px-2 rounded-sm" %>
    <%= submit_tag "Search", class: "px-2 rounded-sm font-light cursor-pointer" %>
  <% end %>
</div>

app/views/films/fav_films.html.erb
<% if not @fav_films.nil? %>
  <div class="container mb-10">
    <h1 class="text-4xl font-light m-0 mt-5">Your Favorites Movies</h1>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
      <% @fav_films.each do |f| %>
        <%= render "film_card", film: f  %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="flex flex-col w-full justify-center mb-10">
    <p class="text-3xl select-none font-light">You don't have any favorite movie yet</p>
    <p class="text-xl select-none font-light">Explore some films</p>
  </div>
<% end %>

app/views/films/index.html.erb
<div class="flex flex-col justify-center shadow-sm">
  <div class="pb-10">

    <div class="flex flex-row justify-center">
      <svg xmlns="http://www.w3.org/2000/svg" class="hidden sm:block h-24 w-24 mr-2" viewBox="0 0 20 20">
        <path fill-rule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm3 2h6v4H7V5zm8 8v2h1v-2h-1zm-2-2H7v4h6v-4zm2 0h1V9h-1v2zm1-4V5h-1v2h1zM5 5v2H4V5h1zm0 4H4v2h1V9zm-1 4h1v2H4v-2z" clip-rule="evenodd" />
      </svg>

      <div class="flex flex-col justify-center">
        <h1 class="text-4xl sm:text-6xl font-light text-gray-700">Search Movies</h1>
        <p class="italic text-xl sm:text-3xl font-light text-gray-400">and save your favorites ones.</p>
      </div>
    </div>

  </div>
  
  <%= form_tag(search_path, method: :get) do %>
    <div class="flex flex-col sm:flex-row m-5 gap-1">
      <%= text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Eg. Jurassic Park", class: "p-5 rounded-md w-full sm:w-96 bg-gray-50" %>
      <%= submit_tag "Search", class: "w-full sm:w-auto px-10 py-5 rounded-md cursor-pointer hover:bg-blue-200 font-light" %>
    </div>
  <% end %>

  <div class="self-center italic pt-3 font-extralight text-gray-500">
    <p>*create an account or sign in to save films.</p>
  </div>
</div>

app/views/films/search.html.erb
<div class="mb-10">
  <h1 class="mx-5 md:mx-0 text-4xl font-light m-0 mt-5"> <%= @film_list["totalResults"] %> results for: <span class="font-extralight"><%= params[:title] %></span></h1>
  <div class="my-5">
    <%= render "pagination" %>
  </div>
  <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
    <% @film_list["Search"].each do |f| %>
      <%= render "film_card", film: f  %>
    <% end %>
  </div>

  <div class="pb-10">
    <%= render "pagination" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavFilms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>

  <body class="h-screen flex justify-center">
    <%= render "/films/navbar" %>
    <div class="flex justify-center mt-10">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container-fluid my-5">
  <% if !(@movies.empty?) %>
    <h6>Find <%= @movies.count %> favorites movies</h6>
    <div class="row">
      <% @movies.each do |movie| %>
        <div class="col-md-3 my-3" id="movie-card">
          <div class="card">
              <%= image_tag movie.poster, class: "img-fluid", crop: :fill %>
          </div>
          <div class="card-footer">
            <h4 class="text-truncate"> <%= movie.title %> </h4>
            <div class="d-flex justify-content-between">
              <h5> <%= movie.tipo %> </h5>
              <h6> <%= movie.year %> </h6>  
            </div>
            <div class="d-flex justify-content-between">
              <%= link_to "Remove favorite", movie_path(movie.id), class: "text-muted", method: :patch %>
              <% if movie.favorite == true %>
                <%= "⭐" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container my-3">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= simple_form_for :search, url: root_path, method: :get do |f| %>
        <div class="d-flex">
          <%= text_field_tag :query,
          params[:query],
          class: "form-control string required",
          placeholder: "Find a movie or serie",
          id: "search_query"
          %>
          <%= submit_tag "Search", class: "btn btn-warning" %>
        </div>        
      <% end %>
    </div>
  </div>
</div>
<div class="container-fluid">
  <% if !(@movies.empty?) %>
    <h6>Find <%= @movies.count %> movies</h6>
    <div class="row">
      <% @movies.each do |movie| %>
        <div class="col-md-3 my-3" id="movie-card">
          <div class="card">
              <%= image_tag movie.poster, class: "img-fluid", crop: :fill %>
          </div>
          <div class="card-footer">
            <h4 class="text-truncate"> <%= movie.title %> </h4>
            <div class="d-flex justify-content-between">
              <h5> <%= movie.tipo %> </h5>
              <h6> <%= movie.year %> </h6>  
            </div>
            <div class="d-flex justify-content-between">
              <%= link_to "Mark as favorite", movie_path(movie.id), class: "text-muted", method: :patch %>
              <% if movie.favorite %>
                <%= "⭐" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>